language: d

# Trusty is Travis' default but reached EOL 2019-04-30
dist: xenial

branches:
  only:
    - /^v\d+\.(x|[\d]+)\.(x|[\d]+)([-|\+](\S+))?$/

os:
  - linux
  - osx

# Latest version of DMD/GDC/LDC + oldest supported
d:
  - dmd
  - ldc
  - dmd-2.085.1
  - ldc-1.14.0

matrix:
  include:
    - d: gdc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gdc-9
      script: gdc-9 --version && dub test --compiler=gdc-9
