name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Run
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest, dmd-2.085.1, ldc-1.14.0 ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1

    - name: 'Build & Test'
      shell: bash
      run: |
        dub test --compiler=$DC -b unittest-cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
